language: node_js
sudo: required
node_js:
  - "node"
env:
  - CXX=g++-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - gcc-4.9
script:
  - npm run lint-js
  - npm test
